
# 服务
server:
  port: 8081


spring:
  application:
    name: spring:manage-web  #服务名称

eureka:
  client:
    # 注册地址
    service-url:
      defaultZone: http://192.168.9.185:2181/eureka/
  instance:
    # ip注册
    prefer-ip-address: true
    # 实例 id 格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# 日志输出
logging:
  level:
    root: info

