
# 服务
server:
  port: 8066


spring:
  # datasource
  datasource:
    url: jdbc:mysql://192.168.9.185:3306/gmall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1024
    type: com.alibaba.druid.pool.DruidDataSource
  # redis 配置
  redis:
    host: 192.168.9.185
    port: 6379
    database: 0
  activemq:
    broker-url: tcp://192.168.9.185:61616
  application:
    name: order-service

activemq:
  listener:
    enable: true


eureka:
  client:
    # 注册地址
    service-url:
      defaultZone: http://192.168.9.185:2181/eureka/
  instance:
    # ip注册
    prefer-ip-address: true
    # 实例 id 格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
# myBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cf.mall.user.domain
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

#showSql
logging:
  level:
    com.cf.mall.manage.mapper: debug
