
# \u670D\u52A1
server:
  port: 8060


spring:
  # datasource
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/gmall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1024
    type: com.alibaba.druid.pool.DruidDataSource

  # dubbo \u7684\u914D\u7F6E
  dubbo:
    application: user-service  #\u670D\u52A1\u540D\u79F0
    registry:
      address: 192.168.9.191:2181 #zookeeper \u6CE8\u518C\u5730\u5740
      protocol: zookeeper # zookeeper\u7684\u901A\u8BAF\u534F\u8BAE\u540D\u79F0
    protocol:
      name: dubbo # dubbo \u7684\u901A\u8BAF\u534F\u8BAE\u540D\u79F0
    base-package: com.cf.mall #dubbo \u7684\u670D\u52A1\u626B\u63CF\u8DEF\u5F84


# myBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cf.mall.user.domain
  configuration:
    map-underscore-to-camel-case: true #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D

#showSql
logging:
  level:
    com.cf.mall.user.mapper: debug
