
# 服务端口
server:
  port: 8060


spring:
  # datasource
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/gmall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1024
    type: com.alibaba.druid.pool.DruidDataSource
  # redis 配置
  redis:
    host: 192.168.9.191
    port: 6379
    database: 0
  # dubbo 配置
  dubbo:
    application: user-service  #名称
    registry:
      address: 192.168.9.191:2181 #zookeeper 注册地址
      protocol: zookeeper # zookeeper通讯协议
    protocol:
      name: dubbo # dubbo 通讯协议
      port: 20880 # 服务调用端口
    base-package: com.cf.mall #dubbo 服务扫描路径


# myBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cf.mall.user.domain
  configuration:
    map-underscore-to-camel-case: true #驼峰命名

#showSql
logging:
  level:
    com.cf.mall.user.mapper: debug
