
# 服务
server:
  port: 8084


spring:
  # 模板的配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: cart-web  # 服务名称

eureka:
  client:
    # 注册地址
    service-url:
      defaultZone: http://192.168.9.185:2181/eureka/
  instance:
    # ip注册
    prefer-ip-address: true
    # 实例 id 格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true




# 日志输出
logging:
  level:
    root: info

