
# 服务
server:
  port: 8084


spring:
  # dubbo 的配置
  dubbo:
    application: cart-web  # 服务名称
    registry:
      address: 192.168.9.191:2181 # zookeeper 注册地址
      protocol: zookeeper # zookeeper的通讯协议名称
    protocol:
      name: dubbo # dubbo 的通讯协议名称
    base-package: com.cf.mall #dubbo 的服务扫描路径
    # 消费配置
    consumer:
      timeout: 2000
      check: false
  # 模板的配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5





# 日志输出
logging:
  level:
    root: info

