
# 服务
server:
  port: 8083
  undertow:
    # 设置IO线程数
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # buffer大小
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true


spring:
  # dubbo 的配置
  dubbo:
    application: search-web  #服务名称
    registry:
      address: 192.168.9.191:2181 #zookeeper 注册地址
      protocol: zookeeper # zookeeper的通讯协议名称
    protocol:
      name: dubbo # dubbo 的通讯协议名称
    base-package: com.cf.mall #dubbo 的服务扫描路径
    #消费配置
    consumer:
      timeout: 10000
      check: false
  # 模板的配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

# 日志输出
logging:
  level:
    root: info

