
# 服务
server:
  port: 8083
  undertow:
    # 设置IO线程数
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # buffer大小
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true


spring:
  # 模板的配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: search-web  #服务名称


eureka:
  client:
    # 注册地址
    service-url:
      defaultZone: http://192.168.9.185:2181/eureka/
  instance:
    # ip注册
    prefer-ip-address: true
    # 实例 id 格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

# 日志输出
logging:
  level:
    root: info

