# 服务
server:
  port: 8080

# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/gmall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1024
    type: com.alibaba.druid.pool.DruidDataSource

# myBatis

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cf.mall.user.domain
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

#showSql
logging:
  level:
    com.cf.mall.user.mapper : debug