
# 服务
server:
  port: 8085


spring:
  # 模板的配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: passport-web

# 日志输出
logging:
  level:
    root: info

eureka:
  client:
    # 注册地址
    service-url:
      defaultZone: http://192.168.9.185:2181/eureka/
  instance:
    # ip注册
    prefer-ip-address: true
    # 实例 id 格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

global-constant:
  security:
    key: passport-web
  app:
    key: 4041463386
    secret: f75907eadc561030a2e0af09e69b1044

